### ISSUE TITLE
btrfs in blendos

### ISSUE THREAD

**Issue by lavilao** [sebanc/linuxloops#10]
Could you please add btrfs support to blendos? Sorry for bothering

**Comment by sebanc** [comment]
Added but be careful not to add subvolumes on paths managed by the akshara initramfs hook (subvolumes are not mounted when it runs)

**Comment by lavilao** [comment]
> Added but be careful not to add subvolumes on paths managed by the akshara initramfs hook (subvolumes are not mounted when it runs)

huh, maybe that why it gave weird issues that it could not find stuff to move when booting the last time I tried it (before you added support).  Anyways thanks!
