### ISSUE TITLE
Linuxloops with ChromeOS Flex: Out of space on '/dev/loop0p2?

### ISSUE THREAD

**Issue by darethehair** [sebanc/linuxloops#13]
I have installed ChromeOS Flex many times with Linuxloops, and it works great!  However, today I went to repeat this on my of my PCs and continued to run into space problems -- I kept reducing the space of my destination image, leaving lots of room, but it still failed on '/dev/loop0p2', which is strange since I could not even get it to show up long enough for me to see what was going on:

```
darren@chuwi:~/Linuxloops$ ls -l;df -h
total 16665024

-rw-r--r-- 1 darren darren 17179869184 Mar 25 11:19 ChromeOS-Flex.img

Filesystem      Size  Used Avail Use% Mounted on
udev            2.8G     0  2.8G   0% /dev
tmpfs           575M  1.6M  574M   1% /run
/dev/sda3        56G   30G   24G  56% /
tmpfs           2.9G   11M  2.8G   1% /dev/shm
tmpfs           5.0M  8.0K  5.0M   1% /run/lock
/dev/sda1       286M  6.0M  280M   3% /boot/efi
tmpfs           575M  104K  575M   1% /run/user/1000
none            2.9G     0  2.9G   0% /home/darren/.linuxloops/chroot/bootstrap/dev/shm
none            2.9G     0  2.9G   0% /home/darren/.linuxloops/chroot/bootstrap/run
none            2.9G     0  2.9G   0% /home/darren/.linuxloops/chroot/bootstrap/tmp
/dev/loop0p1    6.7G  1.3G  5.1G  20% /home/darren/.linuxloops/chroot/bootstrap/isomount/data

dd: error writing '/dev/loop0p2': No space left on device
33+0 records in
32+0 records out
33554432 bytes (34 MB, 32 MiB) copied, 0.251413 s, 133 MB/s
umount: /home/darren/.linuxloops/chroot/bootstrap: target is busy.
umount: /home/darren/.linuxloops/chroot: target is busy.
rm: cannot remove '/home/darren/.linuxloops/chroot/bootstrap': Device or resource busy
```

I have 42gb of space, and so I thought I would have lots of space for installing ChromeOS Flex.  It looks like the Linuxloops has some space overhead during installs (?).

Thanks for any help! :)

**Comment by sebanc** [comment]
I think you still use an old version of the linuxloops script and in recent ChromeOS Flex images the partition 2 size has increased. I fixed that a while ago.

Try again after re-downloading the linuxloops script.
