### ISSUE TITLE
ChromeOS Flex Error on Grub Boot: No Such Module

### ISSUE THREAD

**Issue by darethehair** [sebanc/linuxloops#15]
Successfully installed ChromeOS Flex onto 2010 Toshiba Tecra R700 laptop as the only OS, and then proceeded to try the same thing with LinuxLoops (as I have done many times before on other machines).  Two attempts have failed during Grub boots:

```
error: no such module
error: device name already exists
error: disk 'loop.12' not found
error: you need to load the kernel first
```

Thanks

**Comment by sebanc** [comment]
Are you trying to install on a hdd or to boot from an image ?

If booting from an image, what is your main OS ?

**Comment by darethehair** [comment]
Trying to install to an image in a Linux directory.  The main OS is Linux Mint Debian Edition (LMDE), which is what I use on all my computers in which I dual-boot Linux with ChromeOS Flex.

**Comment by sebanc** [comment]
My guess would be that a first gen intel machine does not use the efi grub2 but the mbr "grub-pc" bootloader.

It seems that the mbr grub can find the image but cannot read the gpt partitions within the linuxloops image.

Could you try to add "insmod part_gpt" at the beginning of the grub config ?

**Comment by darethehair** [comment]
Yes, this worked!  Thanks!  I removed 'rmmod tpm' (which did not apply) and added 'insmod part_gpt' (as you suggested).
