### ISSUE TITLE
Installing windows in a disk image

### ISSUE THREAD

**Issue by suoko** [sebanc/linuxloops#17]
In recommended setups you say "If not already the case, enable grub osprober in your linux distro in order to be able to boot windows from grub." but grub cannot boot a vhd/vhdx image.
I found that https://rmprepusb.com/tutorials/138-directly-boot-from-a-windows-7-8-10-vhd-file-with-grub4dos/ but NBOOT needs to be extracted in a bootable device like a pendrive.
Maybe it's possible to boot NBOOT with grub ?

**Comment by sebanc** [comment]
Grub os-prober will automatically detect windows bootmgrfw.efi in the efi partition and boot it. bootmgrfw.efi will then launch windows boot process that allows booting the vhd/vhdx image.
