### ISSUE TITLE
Network problem when downloading packages

### ISSUE THREAD

**Issue by azliR** [sebanc/linuxloops#18]
Hi! Thank you for your great work! My internet is kind of bad and unstable. When I try to install BlendOS (and others), it fails because of the internet. The timeout seems too short, and there is no retry option. Here's the log:
```
...
Total Download Size:    33.29 MiB
Total Installed Size:  132.65 MiB
Net Upgrade Size:       83.59 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 python-3.12.4-1-...    12.6 MiB   393 KiB/s 00:33 [######################] 100%
 systemd-256.1-1-x86_64.pkg.tar.zst failed to download
 Total ( 2/23)          33.3 MiB   518 KiB/s 01:06 [######################] 100%
error: failed retrieving file 'systemd-256.1-1-x86_64.pkg.tar.zst' from geo.mirror.pkgbuild.com : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```
Oh, and if it's not too much to ask, I wish there was a way to save the last configuration so I don't have to start again from the beginning when it fails. Thanks.

**Comment by sebanc** [comment]
I tried to fix the issue with the mirror selection.

Unfortunately resuming a failed install seems quite difficult but I will think about it.
