### ISSUE TITLE
check size wrongly in / filesystem

### ISSUE THREAD

**Issue by csp5me** [sebanc/linuxloops#21]
hi, i tried linuxloops today and it reports that I don't have enough diskspace.

i ran linuxloops with sudo -E and sudo without -E, both tell me I don't have enough disk space.

I checked and in root / I have around 5GB however on /home I have plenty.
The tool checks wrongly in the / filesystem [sudo privs] instead in /home filesystem where user account is.

**Comment by sebanc** [comment]
Thank you, indeed there was an issue with the script.

I have fixed this issue on the testing branch and will push it shorty on the main branch.

Do not hesitate to verify that it is fixed.

**Comment by sebanc** [comment]
The testing branch changes have been pushed to the linuxloops main branch. Normally this issue should be fixed. Do not hesitate to re-open it if you still encounter this issue.

**Comment by csp5me** [comment]
checked and OK
