### ISSUE TITLE
Brunch installer option fails to install

### ISSUE THREAD

**Issue by darkstalker360** [sebanc/linuxloops#23]
during the installation, after downloading the brunch framework and chromeOS recovery image, the error message "bsdtar failed to set default locale" appears.

**Comment by darkstalker360** [comment]
forgot to mention but this is using the live image

**Comment by sebanc** [comment]
Are you trying to install brunch on a disk or in a disk image ?

"bsdtar failed to set default locale" is actually not a real error and should not stop the install process, is there any other error reported ?

**Comment by darkstalker360** [comment]
I am trying to install brunch to a disk, specifically the internal disk on my laptop

**Comment by darkstalker360** [comment]
I can reflash the live image and try again, and I'll report if there is another error I may not have noticed that stopped installation

> Are you trying to install brunch on a disk or in a disk image ?
> 
> "bsdtar failed to set default locale" is actually not a real error and should not stop the install process, is there any other error reported ?

**Comment by darkstalker360** [comment]
Okay so the installer worked after reflashing the iso to a different usb stick, but it gets stuck at the chromeOS boot logo, I'm installing stable/bobba on a baytrail chromebook (lenuvo yoga 11e chromebook)

**Comment by sebanc** [comment]
I was not able to reproduce this issue, I guess that the recovery image download had failed.

Unfortunately current ChromeOS recovery images do not support baytrail devices.

**Comment by darkstalker360** [comment]
> I was not able to reproduce this issue, I guess that the recovery image download had failed.
> 
> Unfortunately current ChromeOS recovery images do not support baytrail devices.

is there an older release/version I can install that works? if so what is the latest one I can install

**Comment by sebanc** [comment]
If I am not mistaken, baytrail support ended around ChromeOS r94. However, I would not recommend installing such an old version for security reasons.
