### ISSUE TITLE
Lxc fails to install

### ISSUE THREAD

**Issue by suoko** [sebanc/linuxloops#24]
I got an ongoing  'skip to next image" error till it fails completely. That happens when it downloads the arch lxc image (while I'm trying to install brunch actually)
Using WSL

**Comment by sebanc** [comment]
Unfortunately, I cannot reproduce this issue, it seems the lxc server was down when performed the install.

Could you check if it works now ?

I will add secondary lxc servers to solve this.

**Comment by suoko** [comment]
I discovered this is happening on one PC but not another one.
Both PC with win11 + WSL, one can create brunch image just fine, the other fails with lxc error
I do not understand why it tries to download arch image instead of brunch and fails

**Comment by sebanc** [comment]
To avoid polluting users WSL install, the Brunch installation is performed from within an arch rootfs chroot.

All linuxloops does is download the arch rootfs from the lxc image server:
https://sgp1lxdmirror01.do.letsbuildthe.cloud/images/archlinux

I don't understand why one of your pc would not be able to download from this server. Do you have any idea why this would happen ?

**Comment by suoko** [comment]
No clue. Can I enable some logs in your script ?

**Comment by sebanc** [comment]
Could you copy the last lines of the terminal output after a failed install in this issue ?

**Comment by sebanc** [comment]
Also, could you please run `ping -c4 sgp1lxdmirror01.do.letsbuildthe.cloud` from WSL and copy the output in this issue ?

**Comment by suoko** [comment]
@sebanc 

 ./linuxloops -distro Brunch -env "Unstable/Shyvana"  -dst /mnt/c/Users/Public/cros.img -s 14
lsblk: drvfs: not a block device
Creating image file /mnt/c/Users/Public/cros.img...
Downloading lxc rootfs checksum
################################################################################################################# 100.0%################################################################################################################# 100.0%Downloading lxc rootfs image from https://images.linuxcontainers.org/images/archlinux/current/amd64/default/20241009_04%3A18/rootfs.tar.xz...
################################################################################################################# 100.0%################################################################################################################# 100.0%Verifying lxc rootfs checksum
Importing lxc master key
gpg: keybox '/root/.cache/linuxloops/gnupg/pubring.kbx' created
gpg: keyserver receive failed: Server indicated a failure
Downloading lxc rootfs signature
################################################################################################################# 100.0%################################################################################################################# 100.0%Verifying lxc rootfs signature
gpg: Signature made Wed Oct  9 07:03:15 2024 CEST
gpg:                using RSA key E7FB0CAEC8173D669066514CBAEFF88C22F6E216
gpg: Can't check signature: No public key
signature verification failed, trying next image.
Downloading lxc rootfs checksum
################################################################################################################# 100.0%################################################################################################################# 100.0%Downloading lxc rootfs image from https://images.linuxcontainers.org/images/archlinux/current/amd64/default/20241008_04%3A18/rootfs.tar.xz...
################################################################################################################# 100.0%################################################################################################################################################################# 100.0%
Verifying lxc rootfs checksum
Importing lxc master key
gpg: keyserver receive failed: Server indicated a failure
Downloading lxc rootfs signature
################################################################################################################################################################# 100.0%################################################################################################################################################################# 100.0%
Verifying lxc rootfs signature
gpg: Signature made Tue Oct  8 07:03:13 2024 CEST
gpg:                using RSA key E7FB0CAEC8173D669066514CBAEFF88C22F6E216
gpg: Can't check signature: No public key
signature verification failed, trying next image.
Downloading lxc rootfs checksum
################################################################################################################################################################# 100.0%################################################################################################################################################################# 100.0%
Downloading lxc rootfs image from https://images.linuxcontainers.org/images/archlinux/current/amd64/default/20241007_04%3A18/rootfs.tar.xz...
################################################################################################################################################################# 100.0%################################################################################################################################################################# 100.0%
Verifying lxc rootfs checksum
Importing lxc master key
gpg: keyserver receive failed: Server indicated a failure
Downloading lxc rootfs signature
################################################################################################################################################################# 100.0%################################################################################################################################################################# 100.0%
Verifying lxc rootfs signature
gpg: Signature made Mon Oct  7 07:04:04 2024 CEST
gpg:                using RSA key E7FB0CAEC8173D669066514CBAEFF88C22F6E216
gpg: Can't check signature: No public key
signature verification failed, trying next image.
Download of bootstrap image failed.
Installation failed.



root@GIBIX:~# ping -c4 sgp1lxdmirror01.do.letsbuildthe.cloud
PING sgp1lxdmirror01.do.letsbuildthe.cloud (167.71.218.48) 56(84) bytes of data.
64 bytes from 167.71.218.48: icmp_seq=1 ttl=42 time=300 ms

**Comment by sebanc** [comment]
Ok so it is actually the ubuntu PGP keyserver that your computer cannot reach for some reason.

Could you run:
`sed -i 's@hkps://keyserver.ubuntu.com@keys.openpgp.org@g' ./linuxloops`

And try again ?

**Comment by suoko** [comment]
@sebanc 
Same error. Later I'll paste here the results when trying to install a linux distro instead of brunch

**Comment by sebanc** [comment]
What does `ping keys.openpgp.org -c 4` returns ?

**Comment by sebanc** [comment]
I have updated linuxloops, could you please check if the new version solves your issue ?
