### ISSUE TITLE
Add fydeos?

### ISSUE THREAD

**Issue by suoko** [sebanc/linuxloops#25]
For sure the PC version for legacy hw could be very much appreciated.

**Comment by Githubguy132010** [comment]
It could be possible.

**Comment by sebanc** [comment]
Sorry but I am not interested in implementing FydeOS as it is a closed source software.

I would recommend using Bazzite or BlendOS that have Waydroid installation assistants instead.

**Comment by suoko** [comment]
Openfyde is not closed
https://openfyde.io/

**Comment by sebanc** [comment]
Unless I am mistaken Openfyde android container is not open source.

Also, the android container is not available in current releases according to the release notes:
```
 The Android subsystem is currently under major revision and temporarily unavailable.
```

https://github.com/openFyde/overlay-amd64-openfyde/releases/tag/r126
