### ISSUE TITLE
ChromeOS Flex does not boot from the image.

### ISSUE THREAD

**Issue by w-all** [sebanc/linuxloops#26]
ChromeOS Flex does not boot from the image.
First I tried through Windows using Grub2win, but I got a black screen and reboot after selecting an item in grub.
Then I installed Debian and after selecting either a blank grub screen hangs endlessly or reboots after half a minute.
Updated grub from version 2.06 to 2.12 - did not help.
In Debian I used the latest version of linuxboot (I saw that it was updated 14 hours ago from the current time).
I use a Lenovo Ideapad Pro 5 laptop with a Ryzen 7 8845HS processor.

**Comment by sebanc** [comment]
I have just tested booting a ChromeOS-Flex disk image from both an ext4 and an ntfs partition and it works.

However, looking at your CPU I believe your hardware might be too recent for ChromeOS-Flex. Could you try booting an official ChromeOS-Flex usb flashdrive ?

**Comment by w-all** [comment]
Thanks for the reply.
ChromeOS 13 launches normally through brunch.
Okay, I'll try installing ChromeOS-Flex on USB and try to boot.

**Comment by sebanc** [comment]
Unfortunately for now I don't see an other alternative, it seems the issue is related to the ChromeOS-Flex kernel. However, brunch is not very different so chances are the ChromeOS-Flex issue might not take very long to be fixed.

**Comment by w-all** [comment]
JFYI: ChromeOs-Flex deployed using the brunch method started normally.
Perhaps there is little point in such a deployment, since ChromeOS-Flex will not be able to update normally?

**Comment by sebanc** [comment]
You can enable ChromeOS updates in brunch settings but I agree that it will not be 100% ChromeOS-Flex.
