### ISSUE TITLE
Chrome os Flex

### ISSUE THREAD

**Issue by lavilao** [sebanc/linuxloops#3]
First of all, you are a genius this project is awesome. Now to the meat and potatoes, can I use linuxloops with a chrome os flex recovery image? I currently have a dual boot system with windows 10 and manjaro and I would like to be able to boot from the chrome os flex img from the ntfs partition (as linux does not have much space), is this possible? thanks in advice.

**Comment by sebanc** [comment]
Unfortunately, you cannot use linuxloops with chromeos flex as the chromeos flex kernel does not support initramfs.

However, you can use the brunch project with a chromeos flex image to install it on a ntfs partition as dual boot.

**Comment by lavilao** [comment]
Thanks for answer. I currently have a 103 chromeos flex image, is brunch compatible with it? Also I would prefer to boot from an img file if it's possible (currently 9 partitions on a 500gb hdd), oh and last (sorry) given that Chrome os Flex brings a lot of drivers/firmware can I use automatic updates(as the ISO is fully compatible with My laptop) or do I need to download every time I want to update the lastest brunch and chromeos flex image?

**Comment by lavilao** [comment]
Given that there is a ChomeOS Flex entry in the supported distros list, I declare this issue closed.

**Comment by ccchan234** [comment]
> Unfortunately, you cannot use linuxloops with chromeos flex as the chromeos flex kernel does not support initramfs.
> 
> However, you can use the brunch project with a chromeos flex image to install it on a ntfs partition as dual boot.

hi, this is complete opposite to what you suggest to me at another post:
https://github.com/sebanc/brunch/issues/1809#issuecomment-1475194423

i am not novel but i am not familiar with what ntfs/initramfs are.

i simply want to install win10 onto ntfs /w bitlocker(/w secure boot on. i am ok if any OS flex boot need enter bios and disable secure boot),
then install os flex onto the remaining space (either several partitions or one simulated multiple partitions).
and then DUAL BOOT.

as time flies, things change.

may i ask so what's the status now?
thanks

**Comment by sebanc** [comment]
I was mistaken in my previous quote, chromeos flex can actually boot an initramfs, it is just that framebuffer is not enabled in the kernel so there is no display on screen at initramfs stage.

chromeos flex has now been implemented in linuxloops and should allow you to do what you want if bitlocker is disabled on the partition which contains the image. If you use grub2win to boot the image, you will also have to disable secure boot.

**Comment by ccchan234** [comment]
> I was mistaken in my previous quote, chromeos flex can actually boot an initramfs, it is just that framebuffer is not enabled in the kernel so there is no display on screen at initramfs stage.
> 
> chromeos flex has now been implemented in linuxloops and should allow you to do what you want if bitlocker is disabled on the partition which contains the image. If you use grub2win to boot the image, you will also have to disable secure boot.

1 last thing:
i only browsed linuxloop's manual and not too sure, and could only try when have time later.

In the dual boot, should the os flex's partition be 1 single ntfs or "i dont need to care, the installer/linuxloop/script will handle the raw space without partition for me"?

thanks

**Comment by ccchan234** [comment]
> Given that there is a ChomeOS Flex entry in the supported distros list, I declare this issue closed.

hi @lavilao 

did you success in dual booting os flex?
can summarize it in several sentences?

it will be a game changer to many people for os flex.

thanks

**Comment by sebanc** [comment]
You need to make a partition first, linuxloops will only install the image in an existing partition.

**Comment by lavilao** [comment]
@ccchan234 hi, I did not to installed chrome os flex, not due to issues with linuxloops, but because I installed normal brunch as it give me the same advantages but without any of the disadvantages (basically andoid support). Sorry

**Comment by lavilao** [comment]
@ccchan234 dont know if you are still interested but I have just completed the installation of chrome os flex (writting from it). Yes I am able to dual boot it (triple boot in my case). I chose to use a .img file as installation media (its like an iso but writeable). The method is really simple if you have a good internet conection and a fast drive:
1- once you have the free space to install chome os flex (partition or img file) you just open a terminal where the linuxloops file is and write ```sudo bash linuxloops -distro ChromeOS-Flex -env full -dst "path to where you want to install it". Keep in mind that if you are going to use a partition you must be sure what the path to the partition is, otherwise you will delete a wrong partition and will start crying.

**Comment by ccchan234** [comment]
> @ccchan234 dont know if you are still interested but I have just completed the installation of chrome os flex (writting from it). Yes I am able to dual boot it (triple boot in my case). I chose to use a .img file as installation media (its like an iso but writeable). The method is really simple if you have a good internet conection and a fast drive: 1- once you have the free space to install chome os flex (partition or img file) you just open a terminal where the linuxloops file is and write ```sudo bash linuxloops -distro ChromeOS-Flex -env full -dst "path to where you want to install it". Keep in mind that if you are going to use a partition you must be sure what the path to the partition is, otherwise you will delete a wrong partition and will start crying.

thanks for info, may be useful to others too.
thank you.

**Comment by SROG33** [comment]
> @ccchan234 dont know if you are still interested but I have just completed the installation of chrome os flex (writting from it). Yes I am able to dual boot it (triple boot in my case). I chose to use a .img file as installation media (its like an iso but writeable). The method is really simple if you have a good internet conection and a fast drive: 1- once you have the free space to install chome os flex (partition or img file) you just open a terminal where the linuxloops file is and write ```sudo bash linuxloops -distro ChromeOS-Flex -env full -dst "path to where you want to install it". Keep in mind that if you are going to use a partition you must be sure what the path to the partition is, otherwise you will delete a wrong partition and will start crying.

When I tried to install ChromeOS Flex on a partition it said "Linuxloops can only be installed on a full disk."

**Comment by sebanc** [comment]
This message appears if you use a partition name as destination like /dev/sda1 for example and this is not valid.

If you want to dual boot, you need to specify a disk image file path on you filesystem such as /home/user/flex.img.

**Comment by SROG33** [comment]
> This message appears if you use a partition name as destination like /dev/sda1 for example and this is not valid.
> 
> If you want to dual boot, you need to specify a disk image file path on you filesystem such as /home/user/flex.img.

So to dualboot I have to specify the path where the partition is mounted?

**Comment by sebanc** [comment]
Yes you have to provide a file path

**Comment by lavilao** [comment]
It Will create the img file with the OS installed, to generate the grub configs You Will need to type the commands that are outputed at the end of the operation so read before closing the terminal.

**Comment by sebanc** [comment]
> > Yes you have to provide a file path
> 
> Hi. So `sudo bash linuxloops -distro ChromeOS-Flex -env full -dst /home/user/flex.img` will just create flex.img, generate grub entry, which I add than and boot into that file? How file size is managed?

By default the image size is 14 GB, use "-s" option to specify the image file size:
`sudo bash linuxloops -distro ChromeOS-Flex -env full -dst /home/user/flex.img -s 25` to generate a 25GB image file.

**Comment by sebanc** [comment]
Do you have secureboot enabled ? If so, did you enroll the brunch secure boot certificate with "mokutil" tool ?

Also what is your main os ?

**Comment by sebanc** [comment]
I don't really know Fedora Silverblue but if you want to keep secure boot enabled, you should just need to enroll the brunch secure boot certificate with "mokutil" tool.
(last command of the "detailled instructions to install from Linux" Readme)

If you still have it, do you know what was the correct command to update grub with Fedora Silverblue ?

**Comment by sebanc** [comment]
Thanks ! I will try to fix the grub update command when using Silverblue

**Comment by dxrkinfuser44** [comment]
sorry to suddenly revive this but where do you guys get the img file from

**Comment by lavilao** [comment]
> sorry to suddenly revive this but where do you guys get the img file from

The installer will download them for you

**Comment by dxrkinfuser44** [comment]
when i used the installer it gives me a bin file tho

**Comment by lavilao** [comment]
rename it to .img (make sure its the actual bin and not the compressed .tar.xz)

**Comment by dxrkinfuser44** [comment]
thats it aight thank you sm

**Comment by dxrkinfuser44** [comment]
anyone encounter the problem where flex wont run from grub2win (it seems it cant find the right path??)
my img file is on partition L:\, so is the config file, but windows is C:\
from grub2win user section:

```
menuentry 'ChromeOS-Flex' --class 'chromeos-flex' {
	img_path="/ChromeOS-Flex.img"
	img_uuid="98304c2c-3852-4095-a503-7f18ae5d86d8"
	search --no-floppy --set=root --file ${img_path}
	loopback loop ${img_path}
	if [ -f (loop,7)/bootimage.cfg ]; then source (loop,7)/bootimage.cfg; else bootimage=A; fi
	linux (loop,12)/syslinux/vmlinuz.${bootimage} img_uuid=${img_uuid} img_path=${img_path} bootimage=${bootimage} loop.max_part=16 ro quiet splash boot=local noresume noswap loglevel=7 console= cros_efi kvm-intel.vmentry_l1d_flush=always loadpin.enabled=0 loadpin.enforce=0 rootfstype=ramfs cros_debug
	initrd (loop,7)/initramfs.img (loop,7)/firmwares.img (loop,7)/modules.img
}
```
