### ISSUE TITLE
How to reuse .img files

### ISSUE THREAD

**Issue by lavilao** [sebanc/linuxloops#6]
Hi, is there a way to reuse .img files? everytime there is an error (internet or setup wise) linuxloops makes the whole .img file again(which takes a lot of time in HDD), is there a way to just use a img file without the need of creating a new one?Ej: I previously created an empty .img file with truncate of 20G size and I would like to use that same file to install the OS. Thanks in advice.

**Comment by lavilao** [comment]
also the lxc image is redownloaded even if it already exists

**Comment by lavilao** [comment]
also 2.0, cant install arch with gnome.
```
(23/23) Updating the desktop file MIME type cache...
Created symlink /etc/systemd/system/display-manager.service → /usr/lib/systemd/system/gdm.service.
Failed to enable unit, unit cups-browsed.service does not exist.
Failed to install Arch in chroot.
Installation failed.
```
will try now with kde

**Comment by lavilao** [comment]
same issue with kde:
```
(22/22) Updating the desktop file MIME type cache...
Created symlink /etc/systemd/system/display-manager.service → /usr/lib/systemd/system/sddm.service.
Failed to enable unit, unit cups-browsed.service does not exist.
Failed to install Arch in chroot.
Installation failed.
```
I give up

**Comment by sebanc** [comment]
Hi,

Thanks for your report, indeed there was a change in cups-browsed that broke Arch. This issue should now be fixed.

I also reviewed a lot of the script and images creation should now be much faster.

Regarding lxc downloads, I will look into the re-use of cached images but it seems difficult to properly check if everything is ok with a cached image and those images are rather small. You can still modify the download_bootstrap line to suit your needs.

**Comment by lavilao** [comment]
thanks for answering, I did managed to reuse the lxc image of arch by changing the installer ungabunga way (mount the image to 127.0.0.1 and pointing the installer to look there), I guess a more elegant way would be to use something like a checksum like: if arch image is detected then compare the checksums between it and the server image if != check if is decompressible (this would rule out unfinished downloads) if it is offer the user to use it or download a new version, if cheksum is == use the image, else download a new image. Disclaimer I dont know anything about bash.

**Comment by sebanc** [comment]
That's a very good idea, unfortunately I just checked and there is no checksums for the images at linuxcontainers.org.

**Comment by lavilao** [comment]
shame, the only other approarch I can think that does not eliminates the automation part of your script would be to add an argument like -lxc-img where the user would chose the path of the container rootfs, in this case there should also be a test to see if the tar.xz file is decompressible (or just reverse the changes if an error ocurred in the decompression phase really) to avoid the user using corrupted images.

**Comment by lavilao** [comment]
Tried the new installer. Image creation is waaaay faster! Thanks!

**Comment by sebanc** [comment]
Happy new year !

The re-use of previously downloaded lxc image is now implemented. I use curl to retrieve the lxc image size on the server and if it matches the one on the disk it will not re-download the image.

**Comment by lavilao** [comment]
> Happy new year !
> 
> The re-use of previously downloaded lxc image is now implemented. I use curl to retrieve the lxc image size on the server and if it matches the one on the disk it will not re-download the image.

Happy new year!
Thanks for implementing it!
